# Generated by Django 2.2.11 on 2020-04-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.PositiveSmallIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('abreviatura', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.PositiveSmallIntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Origenes',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.PositiveSmallIntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.PositiveSmallIntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Sexos',
            },
        ),
        migrations.CreateModel(
            name='TipoPaciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.PositiveSmallIntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Tipo Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('municipio_res', models.PositiveSmallIntegerField()),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_sintomas', models.DateField(blank=True, null=True)),
                ('fecha_def', models.DateField(blank=True, null=True)),
                ('intubado', models.PositiveSmallIntegerField()),
                ('neumonia', models.PositiveSmallIntegerField()),
                ('edad', models.PositiveSmallIntegerField()),
                ('nacionalidad', models.PositiveSmallIntegerField()),
                ('embarazo', models.PositiveSmallIntegerField()),
                ('habla_lengua_indig', models.PositiveSmallIntegerField()),
                ('diabetes', models.PositiveSmallIntegerField()),
                ('epoc', models.PositiveSmallIntegerField()),
                ('asma', models.PositiveSmallIntegerField()),
                ('inmusupr', models.PositiveSmallIntegerField()),
                ('hipertension', models.PositiveSmallIntegerField()),
                ('otra_com', models.PositiveSmallIntegerField()),
                ('cardiovascular', models.PositiveSmallIntegerField()),
                ('obesidad', models.PositiveSmallIntegerField()),
                ('renal_cronica', models.PositiveSmallIntegerField()),
                ('tabaquismo', models.PositiveSmallIntegerField()),
                ('otro_caso', models.PositiveSmallIntegerField()),
                ('resultado', models.PositiveSmallIntegerField()),
                ('migrante', models.PositiveSmallIntegerField()),
                ('pais_nacionalidad', models.CharField(max_length=100)),
                ('pais_origen', models.CharField(max_length=100)),
                ('uci', models.PositiveSmallIntegerField()),
                ('entidad_nac', models.ForeignKey(on_delete='SET_NULL', related_name='entidadnac', to='conteo.Entidad', to_field='clave')),
                ('entidad_res', models.ForeignKey(on_delete='SET_NULL', related_name='entidadres', to='conteo.Entidad', to_field='clave')),
                ('entidad_um', models.ForeignKey(on_delete='SET_NULL', related_name='entidadum', to='conteo.Entidad', to_field='clave')),
                ('origen', models.ForeignKey(on_delete='SET_NULL', related_name='origen', to='conteo.Origen', to_field='clave')),
                ('sector', models.ForeignKey(on_delete='SET_NULL', related_name='sector', to='conteo.Sector', to_field='clave')),
                ('sexo', models.ForeignKey(on_delete='SET_NULL', related_name='sexo', to='conteo.Sexo', to_field='clave')),
                ('tipo_paciente', models.ForeignKey(on_delete='SET_NULL', related_name='tipopaciente', to='conteo.TipoPaciente', to_field='clave')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('entidad', models.ForeignKey(on_delete='SET_NULL', related_name='entidadmun', to='conteo.Entidad', to_field='clave')),
            ],
        ),
    ]
