# Generated by Django 2.2.11 on 2020-04-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatSiNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.PositiveSmallIntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': "Catálogo Si o No's",
            },
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'verbose_name_plural': 'Municipios'},
        ),
        migrations.AlterField(
            model_name='paciente',
            name='intubado',
            field=models.ForeignKey(on_delete='SET_NULL', related_name='intubado', to='conteo.CatSiNo', to_field='clave'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='neumonia',
            field=models.ForeignKey(on_delete='SET_NULL', related_name='neumonia', to='conteo.CatSiNo', to_field='clave'),
        ),
    ]
