# Generated by Django 2.2.11 on 2020-04-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteo', '0002_auto_20200419_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.PositiveSmallIntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Nacionalidades',
            },
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nacionalidad',
            field=models.ForeignKey(on_delete='SET_NULL', related_name='nacionalidad', to='conteo.Nacionalidad', to_field='clave'),
        ),
    ]
