# Generated by Django 2.2.11 on 2020-04-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteo', '0004_auto_20200419_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='id_registro',
            field=models.CharField(default=22, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete='SET_NULL', related_name='municipiosid', to='conteo.Municipio'),
            preserve_default=False,
        ),
    ]
