# Generated by Django 2.2.11 on 2020-05-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteo', '0005_auto_20200429_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('contagiados', models.PositiveIntegerField()),
                ('sospechosos', models.PositiveIntegerField()),
                ('negativos', models.PositiveIntegerField()),
                ('activos', models.PositiveIntegerField()),
                ('recuperados', models.PositiveIntegerField()),
                ('defunciones_covid', models.PositiveIntegerField()),
                ('defunciones_no_covid', models.PositiveIntegerField()),
                ('intubados', models.PositiveIntegerField()),
                ('intubados_fallecidos', models.PositiveIntegerField()),
                ('sexo_mujer', models.PositiveIntegerField()),
                ('sexo_hombre', models.PositiveIntegerField()),
                ('sexo_no_especificado', models.PositiveIntegerField()),
                ('tipo_paciente_ambulatorio', models.PositiveIntegerField()),
                ('tipo_paciente_hospitalizado', models.PositiveIntegerField()),
                ('tipo_paciente_no_especificado', models.PositiveIntegerField()),
                ('entidad_res', models.ForeignKey(on_delete='SET_NULL', related_name='entidadresResumen', to='conteo.Entidad', to_field='clave')),
                ('municipio', models.ForeignKey(on_delete='SET_NULL', related_name='municipiosidResumen', to='conteo.Municipio')),
            ],
        ),
    ]
