# Generated by Django 2.2.11 on 2020-05-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteo', '0006_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumen',
            name='recuperados',
            field=models.IntegerField(),
        ),
    ]
